### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by farisfaisalthena** [sutanlab/quran-api#12]
Hai, jika kamu bisa. Saya ingin kamu untuk membuat waktu sholat indonesia dan malaysia karena saya tidak dapat menemukan api yang akurat atau jika kamu memiliki api untuk waktu sholat akan mudah dan saya sangat menghargai jika Anda mengirimkan saya tautan

**Comment by sutanlab** [comment]
Hai Faris, waduh kayaknya kalo untuk buat API waktu sholat agak effort buat saya, dimana emang susah nyari sumber yang akurat. apalagi include negara Malaysia juga. Maaf ya, mungkin suatu saat nanti ada orang yang mampu membuatnya.
