### ISSUE TITLE
Error atribut sajda

### ISSUE THREAD

**Issue by humamalamin** [sutanlab/quran-api#2]
atribut sajda tidak konsisten ada yang boolean ada yang object, sehingga saat mau mencoba menampilkan data nya jadi error memiliki 2 type data.
![image](https://user-images.githubusercontent.com/20740163/96671986-5f974e00-138d-11eb-8880-4dbf49a07e07.png)
![image](https://user-images.githubusercontent.com/20740163/96672002-69b94c80-138d-11eb-8a06-aa37ad1f691a.png)

**Comment by sutanlab** [comment]
oke nanti saya cek lagi, terima kasih laporannya ya...

**Comment by sutanlab** [comment]
sepertinya pada ayat ini meta sajda-nya keliru, jadi kaya ada 2 pendapat gitu. `obligatory` (wajibnya) adalah `false`, sedangkan `recommended` nya adalah `true`.
Kira2 kamu bisa bantu cari tahu gak ayat pada surah ini adalah ayat sajda atau bukan? sesuai keputusan sahihnya?

**Comment by humamalamin** [comment]
klo dari [https://khazanah.republika.co.id/berita/q4fge5320/ayat-sajdah-dalam-alquran-bagaimana-cara-mengenalinya](Link) mungkin ini bisa jadi referensi mas. Tapi setelah saya baca untuk surah Al-Insyqaq:21 dia tidak termasuk ayat sajda menurut 4 imam mazhab sih. cuma saran saya mas nya return nya tetep object jangan boolean jadi kalo ada teman-teman lain yang berpendapat berbeda bisa mereka gunakan.

**Comment by sutanlab** [comment]
sipp okay deh, nanti saya konsistenkan semuanya jadi object saja, terima kasih sarannya mas

**Comment by humamalamin** [comment]
sama sama mas.

**Comment by sutanlab** [comment]
Fixed on #4 @humamalamin
