### ISSUE TITLE
Bisakah saya mengambil data dengan parameter Juz?

### ISSUE THREAD

**Issue by ahmadshobirin** [sutanlab/quran-api#20]

**Comment by sutanlab** [comment]
untuk sekarang belum bisa ya mas, paling nnti dijadiin antrian development kedepannya. @ahmadshobirin

**Comment by Ucok23** [comment]
hi @sutanlab dan @ahmadshobirin  , saya menambahkan juz di branch with juz, mungkin bisa dicoba dan dimerge, terima kasih

**Comment by sutanlab** [comment]
Solved in #22 @ahmadshobirin

**Comment by ahmadshobirin** [comment]
terima kasih @sutanlab @Ucok23
